version: '3.6'
services:
  vertx-musicstore:
    build: .
    volumes:
      - type: bind
        source: ${HDIV_CONFIG:-./hdiv/conf}
        target: /hdiv/config
      - type: bind
        source: ${HDIV_AGENT}
        target: /hdiv/hdiv-ee-agent.jar
        read_only: true
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - ${HTTP_PORT:-8080}:8080
    depends_on:
      - "postgres"
      - "mongo"
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=music
      - POSTGRES_PASSWORD=music
      - POSTGRES_DB=musicdb
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
