version: '2'
services:
  vertx-musicstore:
    build: .
    volumes:
      - $HDIV_CONFIG:/hdiv/config
      - $HDIV_AGENT:/hdiv/hdiv-ee-agent.jar
    environment:
      - JAVA_OPTS=$JAVA_OPTS
    ports:
      - $HTTP_PORT:8080
    depends_on:
      - "postgres"
      - "mongo"
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=music
      - POSTGRES_PASSWORD=music
      - POSTGRES_DB=musicdb
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
